### ISSUE TITLE
[BUG] The banner used to save changes in advanced settings is not global after install dashboards-observability

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/dashboards-observability#485] opened 2023-05-25 17:26 UTC
**What is the bug?**
The black banner appended to the bottom of the screen by [react portal](https://oui.opensearch.org/1.0/#/utilities/portal), which shows 1 unsaved setting, Cancel changes, Save changes, is not global any more after install `dashboards-observability`. Now user have to scroll down to see the banner.

The issue is caused by observability plugin modifying global style classes:
* https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/event_analytics/explorer/explorer.scss#L7
* https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/metrics/index.scss#L7

This `opensearch-dashboards-body` is used to wrap the entire body of application. 

**How can one reproduce the bug?**
@joshuali925 found this issue when he tried miki's branch https://github.com/AMoo-Miki/OpenSearch-Dashboards/tree/node-18-webpack-4 and install `dashboards-observability`. This is not related to node 18 and should be reproducible using main under node 14.

0. Run OS, OSD with observability plugin
1. Go to 'Advanced Settings'
2. Change any settings.

**What is the expected behavior?**
Restore the original banner behavior

**Comment by kavilla** [comment] 2023-05-25 17:42
Duplicate of: https://github.com/opensearch-project/dashboards-observability/issues/484

**Closed by kavilla** 2023-05-25 17:42 UTC
Labels: bug, untriaged
